Fix VTK_INSTALL_PREFIX

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15264,39 +15264,39 @@ rm -f core conftest.err conftest.$ac_objext conftest.beam \
         # User may set the install directory for VTK but use
         # the default sensible location if not.
         if test "x$VTK_INSTALL_PREFIX" == "x"; then
-            VTK_INSTALL_PREFIX=/usr/include
+            VTK_INSTALL_PREFIX=/usr
+        else
+            VTK_LIBS="${VTK_INSTALL_PREFIX}/lib"
         fi
 
+        vtk_version_files_to_check="vtkVersionQuick.h vtkVersionMacros.h vtkConfigure.h"
         # Loop through potential vtk installations and get the highest version number
         vtk_version=0
         vtk_include_dir=""
         vtk_version_file=""
-        for i in $(ls -d $VTK_INSTALL_PREFIX/vtk*) $VTK_INCLUDE; do
+        for i in $(ls -d $VTK_INSTALL_PREFIX/include/vtk*) $VTK_INCLUDE; do
+            for filename in $vtk_version_files_to_check; do
             # VTK 6 has a version macros file
-            if test -r $i/vtkVersionMacros.h; then
+              if test -r $i/$filename; then
                 # Get the version number from the macros file
-                this_vtk_version=$(grep -m1 VTK_MAJOR_VERSION $i/vtkVersionMacros.h | sed 's/#define VTK_MAJOR_VERSION //')
+                this_vtk_version=$(grep -m1 VTK_MAJOR_VERSION $i/$filename | sed 's/#define VTK_MAJOR_VERSION //')
                 # Use the latest version available
                 if [ $this_vtk_version -gt $vtk_version ]; then
                    vtk_version=$this_vtk_version
-                   vtk_minor_version=$( grep -m1 VTK_MINOR_VERSION $i/vtkVersionMacros.h | sed 's/#define VTK_MINOR_VERSION //' )
+                   vtk_minor_version=$( grep -m1 VTK_MINOR_VERSION $i/$filename | sed 's/#define VTK_MINOR_VERSION //' )
                    vtk_include_dir=$i
-                   vtk_version_file="vtkVersionMacros.h"
+                   vtk_version_file="$filename"
                 fi
-            # VTK 5 has a configure file that defined the macros
-            elif test -r $i/vtkConfigure.h; then
-                # Get the version number from the configure file
-                this_vtk_version=$(grep -m1 VTK_MAJOR_VERSION $i/vtkConfigure.h | sed 's/#define VTK_MAJOR_VERSION //')
-                # Use the latest version available
-                if [ $this_vtk_version -gt $vtk_version ]; then
-                   vtk_version=$this_vtk_version
-                   vtk_include_dir=$i
-                   vtk_version_file="vtkConfigure.h"
+                if [ "${this_vtk_version}" ]; then
+                  break
                 fi
-            else
-              { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Found VTK folder $i but could not find file to get version." >&5
-printf "%s\n" "$as_me: WARNING: Found VTK folder $i but could not find file to get version." >&2;}
+              fi
+            done
+            if [ "${this_vtk_version}" ]; then
+              break
             fi
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Found VTK folder $i but could not find file to get version." >&5
+printf "%s\n" "$as_me: WARNING: Found VTK folder $i but could not find file to get version." >&2;}
         done
 
         # Add to include path
@@ -16338,15 +16338,16 @@ _ACEOF
 else $as_nop
   if test "x$VTK_LIBS" != "x" ; then
                     LIBS="$LIBS -L$VTK_LIBS"
-                    unset ac_cv_lib_vtkCommonCore_main
-                    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for main in -lvtkCommonCore" >&5
-printf %s "checking for main in -lvtkCommonCore... " >&6; }
-if test ${ac_cv_lib_vtkCommonCore_main+y}
+                    unset ac_cv_lib_vtkCommonCore_${vtk_version}_${vtk_minor_version}_main
+                    as_ac_Lib=`printf "%s\n" "ac_cv_lib_vtkCommonCore-${vtk_version}.${vtk_minor_version}""_main" | $as_tr_sh`
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for main in -lvtkCommonCore-${vtk_version}.${vtk_minor_version}" >&5
+printf %s "checking for main in -lvtkCommonCore-${vtk_version}.${vtk_minor_version}... " >&6; }
+if eval test \${$as_ac_Lib+y}
 then :
   printf %s "(cached) " >&6
 else $as_nop
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lvtkCommonCore  $LIBS"
+LIBS="-lvtkCommonCore-${vtk_version}.${vtk_minor_version}  $LIBS"
 cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
 
@@ -16371,21 +16372,24 @@ return conftest::main ();
 _ACEOF
 if ac_fn_cxx_try_link "$LINENO"
 then :
-  ac_cv_lib_vtkCommonCore_main=yes
+  eval "$as_ac_Lib=yes"
 else $as_nop
-  ac_cv_lib_vtkCommonCore_main=no
+  eval "$as_ac_Lib=no"
 fi
 rm -f core conftest.err conftest.$ac_objext conftest.beam \
     conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_vtkCommonCore_main" >&5
-printf "%s\n" "$ac_cv_lib_vtkCommonCore_main" >&6; }
-if test "x$ac_cv_lib_vtkCommonCore_main" = xyes
+eval ac_res=\$$as_ac_Lib
+	       { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_res" >&5
+printf "%s\n" "$ac_res" >&6; }
+if eval test \"x\$"$as_ac_Lib"\" = x"yes"
 then :
-  printf "%s\n" "#define HAVE_LIBVTKCOMMONCORE 1" >>confdefs.h
+  cat >>confdefs.h <<_ACEOF
+#define `printf "%s\n" "HAVE_LIBvtkCommonCore-${vtk_version}.${vtk_minor_version}" | $as_tr_cpp` 1
+_ACEOF
 
-  LIBS="-lvtkCommonCore $LIBS"
+  LIBS="-lvtkCommonCore-${vtk_version}.${vtk_minor_version} $LIBS"
 
 else $as_nop
 
diff --git a/libadaptivity/configure b/libadaptivity/configure
--- a/libadaptivity/configure
+++ b/libadaptivity/configure
@@ -10249,38 +10249,39 @@ if test "x$enable_vtk" != "xno" ; then
         # User may set the install directory for VTK but use
         # the default sensible location if not.
         if test "x$VTK_INSTALL_PREFIX" == "x"; then
-            VTK_INSTALL_PREFIX=/usr/include
+            VTK_INSTALL_PREFIX=/usr
+        else
+            VTK_LIBS="${VTK_INSTALL_PREFIX}/lib"
         fi
 
+        vtk_version_files_to_check="vtkVersionQuick.h vtkVersionMacros.h vtkConfigure.h"
         # Loop through potential vtk installations and get the highest version number
         vtk_version=0
         vtk_include_dir=""
         vtk_version_file=""
-        for i in $(ls -d $VTK_INSTALL_PREFIX/vtk*) $VTK_INCLUDE; do
+        for i in $(ls -d $VTK_INSTALL_PREFIX/include/vtk*) $VTK_INCLUDE; do
+            for filename in $vtk_version_files_to_check; do
             # VTK 6 has a version macros file
-            if test -r $i/vtkVersionMacros.h; then
+              if test -r $i/$filename; then
                 # Get the version number from the macros file
-                this_vtk_version=$(grep -m1 VTK_MAJOR_VERSION $i/vtkVersionMacros.h | sed 's/#define VTK_MAJOR_VERSION //')
+                this_vtk_version=$(grep -m1 VTK_MAJOR_VERSION $i/$filename | sed 's/#define VTK_MAJOR_VERSION //')
                 # Use the latest version available
                 if [ $this_vtk_version -gt $vtk_version ]; then
                    vtk_version=$this_vtk_version
+                   vtk_minor_version=$( grep -m1 VTK_MINOR_VERSION $i/$filename | sed 's/#define VTK_MINOR_VERSION //' )
                    vtk_include_dir=$i
-                   vtk_version_file="vtkVersionMacros.h"
+                   vtk_version_file="$filename"
                 fi
-            # VTK 5 has a configure file that defined the macros
-            elif test -r $i/vtkConfigure.h; then
-                # Get the version number from the configure file
-                this_vtk_version=$(grep -m1 VTK_MAJOR_VERSION $i/vtkConfigure.h | sed 's/#define VTK_MAJOR_VERSION //')
-                # Use the latest version available
-                if [ $this_vtk_version -gt $vtk_version ]; then
-                   vtk_version=$this_vtk_version
-                   vtk_include_dir=$i
-                   vtk_version_file="vtkConfigure.h"
+                if [ "${this_vtk_version}" ]; then
+                  break
                 fi
-            else
-              { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Found VTK folder $i but could not find file to get version." >&5
-printf "%s\n" "$as_me: WARNING: Found VTK folder $i but could not find file to get version." >&2;}
+              fi
+            done
+            if [ "${this_vtk_version}" ]; then
+              break
             fi
+            { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Found VTK folder $i but could not find file to get version." >&5
+printf "%s\n" "$as_me: WARNING: Found VTK folder $i but could not find file to get version." >&2;}
         done
 
         # Add to include path
